- name: Enabling some Pacman options
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |

      Color
      VerbosePkgLists
      ILoveCandy

    marker: "# {mark} Pacman Tweaks"
    insertafter: '^\[options\]'

- name: Installing artix-archlinux-support
  become: true
  pacman:
    name:
      - artix-archlinux-support
    state: present
    update_cache: yes

- name: Enabling arch linux repos in /etc/pacman.conf
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |

      # Arch
      [extra]
      Include = /etc/pacman.d/mirrorlist-arch

      #[multilib]
      #Include = /etc/pacman.d/mirrorlist-arch

    create: yes

- name: populate pacman keys
  become: true
  command: pacman-key --populate archlinux
  
- name: Updating pacman cache
  become: true
  pacman:
    update_cache: yes

- name: Checking for profile existance
  fail:
    msg: "Profile '{{ target_profile }}' is invalid. Valid options: {{ profiles.keys() | list }}"
  when: target_profile not in profiles

- name: Getting profile packages
  set_fact:
    target_packages: "{{ profiles[target_profile] | map('extract', artix_packages) | flatten }}"

- name: Profile Details
  debug:
    msg: |
      Current Profile: {{ target_profile }}
      Installing {{ target_packages  | length }}: {{ target_packages }}

- name: Installing Profile Packages
  become: true
  pacman:
    name: "{{ target_packages }}"
    state: present 
