- name: Cloning yay Source Code
  ansible.builtin.git:
    repo: "{{ yay.repo }}"
    dest: "{{ yay.dir }}"
    force: yes

- name: Building and installing yay
  command: makepkg -si --noconfirm
  args:
    chdir: "{{ yay.dir }}"
  become_user: "{{ ansible_env.USER }}"
  become: true

